### ISSUE TITLE
MFKey crashes when pressing start

### ISSUE THREAD

**Issue by PlasmaPod** [noproto/FlipperMfkey#12]
https://share.icloud.com/photos/0bbxpXllKPBVWfYr-7d47UskQ

**Comment by noproto** [comment]
@PlasmaPod Thanks for reporting! What firmware is this?

**Comment by noproto** [comment]
I've reproduced the issue, appears to be an issue with the build on certain firmware. Working on isolating the specific issue.

**Comment by PlasmaPod** [comment]
This is the latest Patreon Build of RogueMaster FirmwareSent from my iPhoneOn 26 Mar 2024, at 12:37 AM, Nathan N ***@***.***> wrote:﻿
I've reproduced the issue, appears to be an issue with the build on certain firmware. Working on isolating the specific issue.

**Comment by noproto** [comment]
Thank you for bringing this to my attention @PlasmaPod ! The fix should be included in the next releases of RogueMaster's Patreon build (RM), Momentum, and Unleashed. There have been successful dev build tests on multiple CFWs. RM usually has releases out quite often, so the fix should be available very soon for you. If you don't want to wait until then (should be no more than a day or so), feel free to build this repo and push the application to your device with `ufbt`. Happy cracking! :tada:

**Comment by noproto** [comment]
RM Patreon build released: https://www.patreon.com/posts/101082760
