### ISSUE TITLE
Automatic Builds

### ISSUE THREAD

**Issue by noproto** [noproto/FlipperMfkey#2]
https://github.com/oleksiikutuzov/flipperzero-ufbt-action

**Comment by AloneLiberty** [comment]
You can put link to https://flipc.org/noproto/FlipperMfkey?root=fap so you don't need to worry about building for new API versions

**Comment by noproto** [comment]
@AloneLiberty Our project requires custom compiler flags to run optimally on the Flipper Zero, and I'm not aware of any way to customize those on flipc.org.

Edit: Not anymore.

**Comment by noproto** [comment]
Submitting PR to main FZ firmware to solve this

**Comment by noproto** [comment]
Sent a PR to the FZ default firmware earlier, and it is already being included in RM, Unleashed, etc. Automatic builds are no longer required for this project (as it is being built by firmware developers) and flipc.org will work fine if you choose to trust flipc instead of using `ufbt`.
