### ISSUE TITLE
ValueMutex removal

### ISSUE THREAD

**Issue by RogueMaster** [noproto/FlipperMfkey#4]
Please make changes for valuemutex removal as done by OFW... https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/cf86b2ab406c68143cec2a772011dddb6676dbd7#diff-091e449d65485210eb4fad4b9e05502eea0686acb140317393c434699d35d528

**Comment by noproto** [comment]
Thank you @RogueMaster and xMasterX!
