### ISSUE TITLE
Preload failed, API version mismatch (official firmware 0.79.1)

### ISSUE THREAD

**Issue by 11001010111111101011101010111110** [noproto/FlipperMfkey#5]
I am getting an error when launching the app. "Preload failed, API version mismatch". I'm on the official firmware (0.79.1), running the fap release v1.0.1 of the app.

**Comment by noproto** [comment]
We're working on a significant update to the application for which we will publish .FAPs for every API version. In the meantime, you can compile the source using the latest Flipper Zero firmware tree (move fap/ from this repository to the user application directory as mfkey32/, then use `fbt` to build it).

**Comment by noproto** [comment]
Try again with the latest .FAP release @11001010111111101011101010111110: https://github.com/noproto/FlipperMfkey/releases/tag/v1.0.2 (API 18.2). If you still have issues make sure you are using the latest official firmware.
