### ISSUE TITLE
RogueMaster

### ISSUE THREAD

**Issue by Malazoth** [noproto/FlipperMfkey#7]

**Comment by noproto** [comment]
Is there an issue you are experiencing @Malazoth?

**Comment by Malazoth** [comment]
My apologies. I thought I was making a note to myself and hit the wrong thing altogether. Somewhat new to GitHub (used it before but not terribly long) and the way it works (and the other issues I'm facing with browser compatibility--or non-compatibility) have me thoroughly confused. 

"Never mind!" -- E. Litella

**Comment by noproto** [comment]
All good! I'm going to close this issue out, but feel free to open a new one if you need any help.
