### ISSUE TITLE
Crash with furi_check error message

### ISSUE THREAD

**Issue by LockManipulator** [noproto/FlipperMfkey#8]
I read the key first, then detect reader, then ran mfkey32 and the flipper rebooted and had this message on screen when it turned back on: Flipper crashed and was rebooted furi_check failed

**Comment by noproto** [comment]
Hey @LockManipulator . Thanks for submitting an issue! Here's what I'll need to know:

* Is it reproducible or did it only happen once?
* CFW (custom firmware) or OFW (official)?

If it happens repeatedly, please share your nonces here (or send them to me on Discord - np0) and I'll fix it or make sure it gets fixed.

**Comment by LockManipulator** [comment]
Sorry, forgot to mention I used the latest unleashed firmware! It was happening everytime. But as of 5sec ago, it finished with no crashes when plugged into external power.

**Comment by noproto** [comment]
That indicates that it is a memory usage issue on Unleashed. Thanks for reporting this, I'll look into it.
